{
  "openapi": "3.1.0",
  "tags": [
    {
      "name": "Info",
      "description": "Info operations"
    },
    {
      "name": "Internal Operations",
      "description": "APIs for internal operations"
    },
    {
      "name": "Organizations",
      "description": "APIs for creditor institution, used for inspection of generated flows"
    },
    {
      "name": "PSP",
      "description": "PSP operations"
    },
    {
      "name": "Support",
      "description": "Support operations"
    }
  ],
  "components": {
    "schemas": {
      "AddPaymentRequest": {
        "type": "object",
        "required": [
          "payments"
        ],
        "properties": {
          "payments": {
            "type": "array",
            "maxItems": 1000,
            "minItems": 1,
            "items": {
              "$ref": "#/components/schemas/Payment"
            }
          }
        }
      },
      "CreateFlowRequest": {
        "type": "object",
        "required": [
          "fdr",
          "fdrDate",
          "sender",
          "receiver",
          "regulation",
          "regulationDate",
          "totPayments",
          "sumPayments"
        ],
        "properties": {
          "fdr": {
            "type": "string",
            "example": [
              "2016-08-16pspTest-1178"
            ],
            "pattern": "[a-zA-Z0-9\\-_]{1,35}",
            "description": "[XML NodoInviaFlussoRendicontazione]=[identificativoFlusso]"
          },
          "fdrDate": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-05T09:21:37.810000Z"
            ],
            "description": "[XML NodoInviaFlussoRendicontazione]=[dataOraFlusso]"
          },
          "sender": {
            "$ref": "#/components/schemas/Sender"
          },
          "receiver": {
            "$ref": "#/components/schemas/Receiver"
          },
          "regulation": {
            "type": "string",
            "example": [
              "SEPA - Bonifico xzy"
            ],
            "pattern": "^(.{1,35})$",
            "description": "[XML FlussoRiversamento]=[identificativoUnivocoRegolamento]"
          },
          "regulationDate": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ],
            "description": "[XML FlussoRiversamento]=[dataRegolamento]"
          },
          "bicCodePouringBank": {
            "type": "string",
            "example": [
              "UNCRITMMXXX"
            ],
            "pattern": "^(.{1,35})$",
            "description": "[XML FlussoRiversamento]=[codiceBicBancaDiRiversamento]"
          },
          "totPayments": {
            "type": "integer",
            "format": "int64",
            "example": [
              1
            ],
            "description": "[XML FlussoRiversamento]=[numeroTotalePagamenti]",
            "minimum": 1
          },
          "sumPayments": {
            "type": "number",
            "format": "double",
            "example": [
              0.01
            ],
            "pattern": "^\\d{1,2147483647}([.]\\d{1,2})?$",
            "description": "[XML FlussoRiversamento]=[importoTotalePagamenti]"
          }
        }
      },
      "DeletePaymentRequest": {
        "type": "object",
        "required": [
          "indexList"
        ],
        "properties": {
          "indexList": {
            "type": "array",
            "maxItems": 1000,
            "minItems": 1,
            "items": {
              "type": "integer",
              "format": "int64"
            }
          }
        }
      },
      "ErrorMessage": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "errorId": {
            "type": "string",
            "example": [
              "50905466-1881-457b-b42f-fb7b2bfb1610"
            ]
          },
          "httpStatusCode": {
            "type": "integer",
            "format": "int32",
            "example": [
              500
            ]
          },
          "httpStatusDescription": {
            "type": "string",
            "example": [
              "Internal Server Error"
            ]
          },
          "appErrorCode": {
            "type": "string",
            "example": [
              "FDR-500"
            ]
          },
          "errors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ErrorMessage"
            }
          }
        }
      },
      "FlowByCICreated": {
        "type": "object",
        "properties": {
          "fdr": {
            "type": "string",
            "example": [
              "AAABBB"
            ]
          },
          "organizationId": {
            "type": "string",
            "example": [
              "1"
            ]
          },
          "revision": {
            "type": "integer",
            "format": "int64",
            "example": [
              1
            ]
          },
          "created": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ]
          }
        }
      },
      "FlowByCIPublished": {
        "type": "object",
        "properties": {
          "fdr": {
            "type": "string",
            "example": [
              "AAABBB"
            ]
          },
          "organizationId": {
            "type": "string",
            "example": [
              "1"
            ]
          },
          "revision": {
            "type": "integer",
            "format": "int64",
            "example": [
              1
            ]
          },
          "published": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ]
          }
        }
      },
      "FlowByPSP": {
        "type": "object",
        "properties": {
          "fdr": {
            "type": "string",
            "example": [
              "AAABBB"
            ]
          },
          "pspId": {
            "type": "string",
            "example": [
              "1"
            ]
          },
          "revision": {
            "type": "integer",
            "format": "int64",
            "example": [
              1
            ]
          },
          "published": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ]
          }
        }
      },
      "FlowBySenderAndReceiver": {
        "type": "object",
        "properties": {
          "pspId": {
            "type": "string"
          },
          "organizationId": {
            "type": "string"
          },
          "fdr": {
            "type": "string"
          },
          "revision": {
            "type": "integer",
            "format": "int64"
          },
          "created": {
            "$ref": "#/components/schemas/Instant"
          }
        }
      },
      "GenericResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": [
              "Success"
            ]
          }
        }
      },
      "InfoResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": [
              "pagopa-fdr"
            ]
          },
          "version": {
            "type": "string",
            "example": [
              "1.2.3"
            ]
          },
          "environment": {
            "type": "string",
            "example": [
              "dev"
            ]
          },
          "description": {
            "type": "string",
            "example": [
              "FDR - Flussi di rendicontazione"
            ]
          }
        }
      },
      "Instant": {
        "type": "string",
        "format": "date-time"
      },
      "Metadata": {
        "type": "object",
        "properties": {
          "pageSize": {
            "type": "integer",
            "format": "int32",
            "example": [
              25
            ]
          },
          "pageNumber": {
            "type": "integer",
            "format": "int32",
            "example": [
              1
            ]
          },
          "totPage": {
            "type": "integer",
            "format": "int32",
            "example": [
              3
            ]
          }
        }
      },
      "PaginatedFlowsBySenderAndReceiverResponse": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/components/schemas/Metadata"
          },
          "count": {
            "type": "integer",
            "format": "int64",
            "example": [
              100
            ]
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FlowBySenderAndReceiver"
            }
          }
        }
      },
      "PaginatedFlowsCreatedResponse": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/components/schemas/Metadata"
          },
          "count": {
            "type": "integer",
            "format": "int64",
            "example": [
              100
            ]
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FlowByCICreated"
            }
          }
        }
      },
      "PaginatedFlowsPublishedResponse": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/components/schemas/Metadata"
          },
          "count": {
            "type": "integer",
            "format": "int64",
            "example": [
              100
            ]
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FlowByCIPublished"
            }
          }
        }
      },
      "PaginatedFlowsResponse": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/components/schemas/Metadata"
          },
          "count": {
            "type": "integer",
            "format": "int64",
            "example": [
              100
            ]
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FlowByPSP"
            }
          }
        }
      },
      "PaginatedPaymentsResponse": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/components/schemas/Metadata"
          },
          "count": {
            "type": "integer",
            "format": "int64",
            "example": [
              100
            ]
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Payment"
            }
          }
        }
      },
      "Payment": {
        "type": "object",
        "required": [
          "index",
          "iuv",
          "iur",
          "idTransfer",
          "pay",
          "payStatus",
          "payDate"
        ],
        "properties": {
          "index": {
            "type": "integer",
            "format": "int64",
            "example": [
              1
            ],
            "description": "Identificativo del pagamento univoco nel flusso",
            "minimum": 1
          },
          "iuv": {
            "type": "string",
            "example": [
              "abcdefg"
            ],
            "pattern": "^(.{1,35})$",
            "description": "[XML FlussoRiversamento]=[datiSingoliPagamenti.identificativoUnivocoVersamento]"
          },
          "iur": {
            "type": "string",
            "example": [
              "abcdefg"
            ],
            "pattern": "^(.{1,35})$",
            "description": "[XML FlussoRiversamento]=[datiSingoliPagamenti.identificativoUnivocoRiscossione]"
          },
          "idTransfer": {
            "type": "integer",
            "format": "int64",
            "example": [
              1
            ],
            "description": "[XML FlussoRiversamento]=[datiSingoliPagamenti.indiceDatiSingoloPagamento]",
            "maximum": 5,
            "minimum": 1
          },
          "pay": {
            "type": "number",
            "format": "double",
            "example": [
              0.01
            ],
            "pattern": "^\\d{1,2147483647}([.]\\d{1,2})?$",
            "description": "[XML FlussoRiversamento]=[datiSingoliPagamenti.singoloImportoPagato]"
          },
          "payStatus": {
            "$ref": "#/components/schemas/PaymentStatusEnum",
            "type": "string",
            "example": [
              "EXECUTED"
            ],
            "description": "[XML FlussoRiversamento]=[datiSingoliPagamenti.codiceEsitoSingoloPagamento] \n0 -> EXECUTED\n3 -> REVOKED\n9 -> NO_RPT\n4 -> STAND_IN\n8 -> STAND_IN_NO_RPT"
          },
          "payDate": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-02-03T12:00:30.900000Z"
            ],
            "description": "[XML FlussoRiversamento]=[datiSingoliPagamenti.dataEsitoSingoloPagamento]"
          }
        }
      },
      "PaymentStatusEnum": {
        "type": "string",
        "enum": [
          "EXECUTED",
          "REVOKED",
          "NO_RPT",
          "STAND_IN",
          "STAND_IN_NO_RPT"
        ]
      },
      "Receiver": {
        "type": "object",
        "required": [
          "id",
          "organizationId",
          "organizationName"
        ],
        "properties": {
          "id": {
            "type": "string",
            "example": [
              "APPBIT2B"
            ],
            "pattern": "^(.{1,35})$",
            "description": "[XML FlussoRiversamento]=[istitutoRicevente.identificativoUnivocoRicevente.codiceIdentificativoUnivoco]"
          },
          "organizationId": {
            "type": "string",
            "example": [
              "20000000001"
            ],
            "pattern": "^(.{1,35})$",
            "description": "[XML NodoInviaFlussoRendicontazione]=[identificativoDominio]"
          },
          "organizationName": {
            "type": "string",
            "example": [
              "Comune di xyz"
            ],
            "pattern": "^(.{1,140})$",
            "description": "[XML FlussoRiversamento]=[istitutoRicevente.denominazioneRicevente]"
          }
        }
      },
      "ReportingFlowStatusEnum": {
        "type": "string",
        "enum": [
          "CREATED",
          "INSERTED",
          "PUBLISHED"
        ]
      },
      "Sender": {
        "type": "object",
        "required": [
          "type",
          "id",
          "pspId",
          "pspName",
          "pspBrokerId",
          "channelId"
        ],
        "properties": {
          "type": {
            "$ref": "#/components/schemas/SenderTypeEnum",
            "type": "string",
            "example": [
              "LEGAL_PERSON"
            ],
            "description": "[XML FlussoRiversamento]=[istitutoMittente.identificativoUnivocoMittente.tipoIdentificativoUnivoco] \nG -> LEGAL_PERSON\nA -> ABI_CODE\nB -> BIC_CODE"
          },
          "id": {
            "type": "string",
            "example": [
              "SELBIT2B"
            ],
            "pattern": "^(.{1,35})$",
            "description": "[XML FlussoRiversamento]=[istitutoMittente.identificativoUnivocoMittente.codiceIdentificativoUnivoco]"
          },
          "pspId": {
            "type": "string",
            "example": [
              "60000000001"
            ],
            "pattern": "^(.{1,35})$",
            "description": "[XML NodoInviaFlussoRendicontazione]=[identificativoPSP]"
          },
          "pspName": {
            "type": "string",
            "example": [
              "Bank"
            ],
            "pattern": "^(.{3,70})$",
            "description": "[XML FlussoRiversamento]=[istitutoMittente.denominazioneMittente]"
          },
          "pspBrokerId": {
            "type": "string",
            "example": [
              "70000000001"
            ],
            "pattern": "^(.{1,35})$",
            "description": "[XML NodoInviaFlussoRendicontazione]=[identificativoIntermediarioPSP]"
          },
          "channelId": {
            "type": "string",
            "example": [
              "80000000001"
            ],
            "pattern": "^(.{1,35})$",
            "description": "[XML NodoInviaFlussoRendicontazione]=[identificativoCanale]"
          },
          "password": {
            "type": "string",
            "deprecated": true,
            "example": [
              "1234567890"
            ],
            "pattern": "^(\\w{8,15})$",
            "description": "[XML NodoInviaFlussoRendicontazione]=[password]"
          }
        }
      },
      "SenderTypeEnum": {
        "type": "string",
        "enum": [
          "LEGAL_PERSON",
          "ABI_CODE",
          "BIC_CODE"
        ]
      },
      "SingleFlowCreatedResponse": {
        "type": "object",
        "properties": {
          "status": {
            "$ref": "#/components/schemas/ReportingFlowStatusEnum",
            "type": "string",
            "example": [
              "CREATED"
            ]
          },
          "revision": {
            "type": "integer",
            "format": "int64",
            "example": [
              4
            ]
          },
          "created": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ]
          },
          "updated": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ]
          },
          "fdr": {
            "type": "string",
            "example": [
              "2016-08-16pspTest-1178"
            ]
          },
          "fdrDate": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-05T09:21:37.810000Z"
            ]
          },
          "regulation": {
            "type": "string",
            "example": [
              "SEPA - Bonifico xzy"
            ]
          },
          "regulationDate": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ]
          },
          "bicCodePouringBank": {
            "type": "string",
            "example": [
              "UNCRITMMXXX"
            ]
          },
          "sender": {
            "$ref": "#/components/schemas/Sender"
          },
          "receiver": {
            "$ref": "#/components/schemas/Receiver"
          },
          "computedTotPayments": {
            "type": "integer",
            "format": "int64",
            "example": [
              100
            ]
          },
          "computedSumPayments": {
            "type": "number",
            "format": "double",
            "example": [
              100.9
            ]
          },
          "totPayments": {
            "type": "integer",
            "format": "int64",
            "example": [
              100
            ]
          },
          "sumPayments": {
            "type": "number",
            "format": "double",
            "example": [
              100.9
            ]
          }
        }
      },
      "SingleFlowResponse": {
        "type": "object",
        "properties": {
          "status": {
            "$ref": "#/components/schemas/ReportingFlowStatusEnum",
            "type": "string",
            "example": [
              "CREATED"
            ]
          },
          "revision": {
            "type": "integer",
            "format": "int64",
            "example": [
              4
            ]
          },
          "created": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ]
          },
          "updated": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ]
          },
          "fdr": {
            "type": "string",
            "example": [
              "2016-08-16pspTest-1178"
            ]
          },
          "fdrDate": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-05T09:21:37.810000Z"
            ]
          },
          "regulation": {
            "type": "string",
            "example": [
              "SEPA - Bonifico xzy"
            ]
          },
          "regulationDate": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ]
          },
          "bicCodePouringBank": {
            "type": "string",
            "example": [
              "UNCRITMMXXX"
            ]
          },
          "sender": {
            "$ref": "#/components/schemas/Sender"
          },
          "receiver": {
            "$ref": "#/components/schemas/Receiver"
          },
          "published": {
            "$ref": "#/components/schemas/Instant",
            "type": "string",
            "example": [
              "2023-04-03T12:00:30.900000Z"
            ]
          },
          "computedTotPayments": {
            "type": "integer",
            "format": "int64",
            "example": [
              100
            ]
          },
          "computedSumPayments": {
            "type": "number",
            "format": "double",
            "example": [
              100.9
            ]
          },
          "totPayments": {
            "type": "integer",
            "format": "int64",
            "example": [
              100
            ]
          },
          "sumPayments": {
            "type": "number",
            "format": "double",
            "example": [
              100.9
            ]
          }
        }
      }
    }
  },
  "paths": {
    "/info": {
      "get": {
        "summary": "Health-check",
        "operationId": "IInfoController.healthCheck",
        "tags": [
          "Info"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InfoResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "errorId": "50905466-1881-457b-b42f-fb7b2bfb1610",
                  "httpStatusCode": 500,
                  "httpStatusDescription": "Internal Server Error",
                  "appErrorCode": "FDR-0500",
                  "errors": [
                    {
                      "message": "An unexpected error has occurred. Please contact support."
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/internal/psps/{pspId}/created/fdrs/{fdr}/organizations/{organizationId}": {
      "get": {
        "summary": "Get created fdr",
        "operationId": "IInternalOperationsController.getSingleFlowNotInPublishedStatusForInternalUse",
        "tags": [
          "Internal Operations"
        ],
        "parameters": [
          {
            "name": "fdr",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "organizationId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "pspId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SingleFlowCreatedResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 400,
                  "httpStatusDescription": "Bad Request",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "path": "<detail.path.if-exist>",
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 404,
                  "httpStatusDescription": "Not Found",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "errorId": "50905466-1881-457b-b42f-fb7b2bfb1610",
                  "httpStatusCode": 500,
                  "httpStatusDescription": "Internal Server Error",
                  "appErrorCode": "FDR-0500",
                  "errors": [
                    {
                      "message": "An unexpected error has occurred. Please contact support."
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/internal/psps/{pspId}/fdrs/{fdr}": {
      "delete": {
        "summary": "Delete fdr",
        "operationId": "IInternalOperationsController.deleteExistingFlowForInternalUse",
        "tags": [
          "Internal Operations"
        ],
        "parameters": [
          {
            "name": "fdr",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "pspId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GenericResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 400,
                  "httpStatusDescription": "Bad Request",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "path": "<detail.path.if-exist>",
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 404,
                  "httpStatusDescription": "Not Found",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "errorId": "50905466-1881-457b-b42f-fb7b2bfb1610",
                  "httpStatusCode": 500,
                  "httpStatusDescription": "Internal Server Error",
                  "appErrorCode": "FDR-0500",
                  "errors": [
                    {
                      "message": "An unexpected error has occurred. Please contact support."
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create fdr",
        "operationId": "IInternalOperationsController.createEmptyFlowForInternalUse",
        "tags": [
          "Internal Operations"
        ],
        "parameters": [
          {
            "name": "fdr",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "[a-zA-Z0-9\\-_]{1,35}"
            }
          },
          {
            "name": "pspId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateFlowRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GenericResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 400,
                  "httpStatusDescription": "Bad Request",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "path": "<detail.path.if-exist>",
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 404,
                  "httpStatusDescription": "Not Found",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "errorId": "50905466-1881-457b-b42f-fb7b2bfb1610",
                  "httpStatusCode": 500,
                  "httpStatusDescription": "Internal Server Error",
                  "appErrorCode": "FDR-0500",
                  "errors": [
                    {
                      "message": "An unexpected error has occurred. Please contact support."
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/internal/psps/{pspId}/fdrs/{fdr}/payments/add": {
      "put": {
        "summary": "Add payments to fdr",
        "operationId": "IInternalOperationsController.addPaymentToExistingFlowForInternalUse",
        "tags": [
          "Internal Operations"
        ],
        "parameters": [
          {
            "name": "fdr",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "pspId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddPaymentRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GenericResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 400,
                  "httpStatusDescription": "Bad Request",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "path": "<detail.path.if-exist>",
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 404,
                  "httpStatusDescription": "Not Found",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "errorId": "50905466-1881-457b-b42f-fb7b2bfb1610",
                  "httpStatusCode": 500,
                  "httpStatusDescription": "Internal Server Error",
                  "appErrorCode": "FDR-0500",
                  "errors": [
                    {
                      "message": "An unexpected error has occurred. Please contact support."
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/internal/psps/{pspId}/fdrs/{fdr}/payments/del": {
      "put": {
        "summary": "Delete payments to fdr",
        "operationId": "IInternalOperationsController.deletePaymentFromExistingFlowForInternalUse",
        "tags": [
          "Internal Operations"
        ],
        "parameters": [
          {
            "name": "fdr",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "pspId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeletePaymentRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GenericResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 400,
                  "httpStatusDescription": "Bad Request",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "path": "<detail.path.if-exist>",
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 404,
                  "httpStatusDescription": "Not Found",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "errorId": "50905466-1881-457b-b42f-fb7b2bfb1610",
                  "httpStatusCode": 500,
                  "httpStatusDescription": "Internal Server Error",
                  "appErrorCode": "FDR-0500",
                  "errors": [
                    {
                      "message": "An unexpected error has occurred. Please contact support."
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/internal/psps/{pspId}/fdrs/{fdr}/publish": {
      "post": {
        "summary": "Publish fdr",
        "operationId": "IInternalOperationsController.publishFlowForInternalUse",
        "tags": [
          "Internal Operations"
        ],
        "parameters": [
          {
            "name": "fdr",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "pspId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GenericResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 400,
                  "httpStatusDescription": "Bad Request",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "path": "<detail.path.if-exist>",
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 404,
                  "httpStatusDescription": "Not Found",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "errorId": "50905466-1881-457b-b42f-fb7b2bfb1610",
                  "httpStatusCode": 500,
                  "httpStatusDescription": "Internal Server Error",
                  "appErrorCode": "FDR-0500",
                  "errors": [
                    {
                      "message": "An unexpected error has occurred. Please contact support."
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/internal/psps/{pspId}/iur/{iur}": {
      "get": {
        "summary": "Get all payments by psp id and iur",
        "operationId": "ISupportController.getByIur",
        "tags": [
          "Support"
        ],
        "parameters": [
          {
            "name": "iur",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "^(.{1,35})$"
            }
          },
          {
            "name": "pspId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "^(.{1,35})$"
            }
          },
          {
            "name": "createdFrom",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/Instant"
            }
          },
          {
            "name": "createdTo",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/Instant"
            }
          },
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int64",
              "default": 1,
              "minimum": 1
            }
          },
          {
            "name": "size",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int64",
              "default": 1000,
              "minimum": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginatedFlowsBySenderAndReceiverResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 400,
                  "httpStatusDescription": "Bad Request",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "path": "<detail.path.if-exist>",
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 404,
                  "httpStatusDescription": "Not Found",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "errorId": "50905466-1881-457b-b42f-fb7b2bfb1610",
                  "httpStatusCode": 500,
                  "httpStatusDescription": "Internal Server Error",
                  "appErrorCode": "FDR-0500",
                  "errors": [
                    {
                      "message": "An unexpected error has occurred. Please contact support."
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/internal/psps/{pspId}/iuv/{iuv}": {
      "get": {
        "summary": "Get all payments by psp id and iuv",
        "operationId": "ISupportController.getByIuv",
        "tags": [
          "Support"
        ],
        "parameters": [
          {
            "name": "iuv",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "^(.{1,35})$"
            }
          },
          {
            "name": "pspId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "^(.{1,35})$"
            }
          },
          {
            "name": "createdFrom",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/Instant"
            }
          },
          {
            "name": "createdTo",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/Instant"
            }
          },
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int64",
              "default": 1,
              "minimum": 1
            }
          },
          {
            "name": "size",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int64",
              "default": 1000,
              "minimum": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginatedFlowsBySenderAndReceiverResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 400,
                  "httpStatusDescription": "Bad Request",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "path": "<detail.path.if-exist>",
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "example": {
                  "httpStatusCode": 404,
                  "httpStatusDescription": "Not Found",
                  "appErrorCode": "FDR-XXXX",
                  "errors": [
                    {
                      "message": "<detail.message>"
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "errorId": "50905466-1881-457b-b42f-fb7b2bfb1610",
                  "httpStatusCode": 500,
                  "httpStatusDescription": "Internal Server Error",
                  "appErrorCode": "FDR-0500",
                  "errors": [
                    {
                      "message": "An unexpected error has occurred. Please contact support."
                    }
                  ]
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "info": {
    "title": "FDR - Flussi di Rendicontazione",
    "description": "Manage FDR (aka \"Flussi di Rendicontazione\") exchanged between PSP and EC\n\n## OPERATIONAL ERROR CODES\n\n<details><summary>Details</summary>\nNAME | CODE | DESCRIPTION\n- | - | -\n**FDR-0500** | *ERROR* | -\n**FDR-1000** | *BAD_REQUEST* | -\n**FDR-1001** | *BAD_REQUEST_INPUT_JSON* | -\n**FDR-1002** | *BAD_REQUEST_INPUT_JSON_INSTANT* | -\n**FDR-1003** | *BAD_REQUEST_INPUT_JSON_ENUM* | -\n**FDR-1004** | *BAD_REQUEST_INPUT_JSON_DESERIALIZE_ERROR* | -\n**FDR-1005** | *BAD_REQUEST_INPUT_JSON_NON_VALID_FORMAT* | -\n**FDR-2000** | *PSP_UNKNOWN* | -\n**FDR-2001** | *PSP_NOT_ENABLED* | -\n**FDR-2002** | *BROKER_UNKNOWN* | -\n**FDR-2003** | *BROKER_NOT_ENABLED* | -\n**FDR-2004** | *CHANNEL_UNKNOWN* | -\n**FDR-2005** | *CHANNEL_NOT_ENABLED* | -\n**FDR-2006** | *CHANNEL_BROKER_WRONG_CONFIG* | -\n**FDR-2007** | *CHANNEL_PSP_WRONG_CONFIG* | -\n**FDR-2008** | *EC_UNKNOWN* | -\n**FDR-2009** | *EC_NOT_ENABLED* | -\n**FDR-3001** | *REPORTING_FLOW_NOT_FOUND* | -\n**FDR-3002** | *REPORTING_FLOW_ALREADY_EXIST* | -\n**FDR-3003** | *REPORTING_FLOW_WRONG_ACTION* | -\n**FDR-3004** | *REPORTING_FLOW_PSP_ID_NOT_MATCH* | -\n**FDR-3005** | *REPORTING_FLOW_PAYMENT_SAME_INDEX_IN_SAME_REQUEST* | -\n**FDR-3006** | *REPORTING_FLOW_PAYMENT_DUPLICATE_INDEX* | -\n**FDR-3007** | *REPORTING_FLOW_PAYMENT_NO_MATCH_INDEX* | -\n**FDR-3008** | *REPORTING_FLOW_NAME_DATE_WRONG_FORMAT* | -\n**FDR-3009** | *REPORTING_FLOW_NAME_PSP_WRONG_FORMAT* | -\n**FDR-3010** | *REPORTING_FLOW_NAME_NOT_MATCH* | -\n**FDR-4001** | *REPORTING_FLOW_WRONG_TOT_PAYMENT* | -\n**FDR-4002** | *REPORTING_FLOW_WRONG_SUM_PAYMENT* | -\n**FDR-5000** | *FILE_UTILS_CONVERSION_ERROR* | -\n**FDR-5001** | *FILE_UTILS_FILE_NOT_FOUND* | -\n**FDR-5002** | *COMPRESS_JSON* | -\n",
    "termsOfService": "https://www.pagopa.gov.it/",
    "version": "1.1.10"
  },
  "servers": [
    {
      "url": "${host}",
      "description": "Environment host"
    },
    {
      "url": "http://localhost:8080/",
      "description": "Localhost"
    }
  ]
}
